name: posterr_design_system
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/logo.png
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf
        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 700

